"""
PDF Generator for MSME Copilot Strategy Reports
Creates beautiful, professional PDF reports from strategy data
"""
from fpdf import FPDF
from datetime import datetime, timedelta
from typing import Dict, Any, List
import re


def sanitize_text(text: str) -> str:
    """Sanitize text to remove/replace unsupported Unicode characters"""
    if not text:
        return ""
    # Replace Rupee symbol with Rs.
    text = text.replace("₹", "Rs.")
    # Replace other common unicode that might cause issues
    text = text.replace("…", "...")
    text = text.replace("–", "-")
    text = text.replace("—", "-")
    text = text.replace("'", "'")
    text = text.replace("'", "'")
    text = text.replace(""", '"')
    text = text.replace(""", '"')
    text = text.replace("•", "-")
    # Remove any remaining non-ASCII characters that might cause issues
    text = text.encode('latin-1', errors='replace').decode('latin-1')
    return text


class StrategyReportPDF(FPDF):
    """Custom PDF class for strategy reports"""
    
    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=20)
        
    def header(self):
        # Logo area - gradient effect with colored rectangle
        self.set_fill_color(102, 126, 234)  # Primary blue
        self.rect(0, 0, 210, 35, 'F')
        
        # Gradient overlay
        self.set_fill_color(118, 75, 162)  # Purple
        for i in range(35):
            alpha = i / 35
            r = int(102 + (118 - 102) * alpha)
            g = int(126 + (75 - 126) * alpha)
            b = int(234 + (162 - 234) * alpha)
            self.set_fill_color(r, g, b)
            self.rect(0, i, 210, 1, 'F')
        
        # Title
        self.set_text_color(255, 255, 255)
        self.set_font('Helvetica', 'B', 20)
        self.set_y(10)
        self.cell(0, 10, 'MSME Copilot', align='C', ln=True)
        
        # Subtitle
        self.set_font('Helvetica', '', 10)
        self.cell(0, 5, 'AI-Powered Business Strategy Report', align='C', ln=True)
        
        # Reset for content
        self.set_y(45)
        self.set_text_color(0, 0, 0)
        
    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by MSME Copilot AI', align='C')
    
    def chapter_title(self, title: str, emoji: str = ""):
        """Add a chapter title with styling"""
        title = sanitize_text(title)
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(102, 126, 234)
        self.cell(0, 10, f'{emoji} {title}', ln=True)
        self.set_text_color(0, 0, 0)
        # Underline
        self.set_draw_color(102, 126, 234)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)
    
    def section_title(self, title: str):
        """Add a section subtitle"""
        title = sanitize_text(title)
        self.set_font('Helvetica', 'B', 11)
        self.set_text_color(60, 60, 60)
        self.cell(0, 8, title, ln=True)
        self.set_text_color(0, 0, 0)
        self.ln(2)
    
    def body_text(self, text: str):
        """Add body text"""
        text = sanitize_text(text)
        self.set_font('Helvetica', '', 10)
        self.multi_cell(0, 6, text)
        self.ln(3)
    
    def bullet_point(self, text: str, indent: int = 10):
        """Add a bullet point"""
        text = sanitize_text(text)
        self.set_font('Helvetica', '', 10)
        self.set_x(indent)
        self.cell(5, 6, chr(149))  # Bullet character
        self.multi_cell(0, 6, text)
    
    def checkbox_item(self, text: str, checked: bool = False):
        """Add a checkbox item"""
        text = sanitize_text(text)
        self.set_font('Helvetica', '', 10)
        self.set_x(15)
        box = "[x]" if checked else "[ ]"
        self.cell(10, 6, box)
        self.multi_cell(0, 6, text)
    
    def add_table(self, headers: List[str], rows: List[List[str]], col_widths: List[int] = None):
        """Add a simple table"""
        # Sanitize headers
        headers = [sanitize_text(h) for h in headers]
        # Sanitize rows
        sanitized_rows = []
        for row in rows:
            sanitized_rows.append([sanitize_text(cell) for cell in row])
        rows = sanitized_rows
        
        if col_widths is None:
            col_widths = [190 // len(headers)] * len(headers)
        
        # Header
        self.set_font('Helvetica', 'B', 9)
        self.set_fill_color(102, 126, 234)
        self.set_text_color(255, 255, 255)
        for i, header in enumerate(headers):
            self.cell(col_widths[i], 8, header, border=1, fill=True, align='C')
        self.ln()
        
        # Rows
        self.set_font('Helvetica', '', 9)
        self.set_text_color(0, 0, 0)
        fill = False
        for row in rows:
            if fill:
                self.set_fill_color(245, 245, 250)
            else:
                self.set_fill_color(255, 255, 255)
            
            max_lines = 1
            for i, cell in enumerate(row):
                # Calculate lines needed
                lines = len(cell) // (col_widths[i] // 2) + 1
                max_lines = max(max_lines, lines)
            
            for i, cell in enumerate(row):
                self.cell(col_widths[i], 7 * max_lines, cell[:50], border=1, fill=True)
            self.ln()
            fill = not fill
        
        self.ln(5)
    
    def priority_badge(self, priority: str):
        """Get priority indicator"""
        indicators = {
            'high': '[HIGH]',
            'medium': '[MED]',
            'low': '[LOW]'
        }
        return indicators.get(priority.lower(), '[--]')


def generate_strategy_pdf(strategy: Dict[str, Any]) -> bytes:
    """Generate a PDF from strategy data and return as bytes"""
    
    pdf = StrategyReportPDF()
    pdf.add_page()
    
    today = datetime.now()
    
    # Executive Summary
    pdf.chapter_title("Executive Summary", "")
    pdf.body_text(strategy.get('executive_summary', 'Strategy overview not available.'))
    
    # Key Opportunities
    pdf.chapter_title("Key Opportunities", "")
    opportunities = strategy.get('key_opportunities', [])
    for opp in opportunities:
        priority = pdf.priority_badge(opp.get('priority', 'medium'))
        pdf.section_title(f"{priority} {opp.get('opportunity', 'Opportunity')}")
        pdf.body_text(f"Potential Gain: {opp.get('potential_gain', 'N/A')}")
    
    # Immediate Actions
    pdf.add_page()
    pdf.chapter_title("Immediate Actions", "")
    
    actions = strategy.get('immediate_actions', [])
    if actions:
        headers = ['Action', 'Timeline', 'Expected Outcome', 'Resources']
        rows = []
        for action in actions:
            rows.append([
                action.get('action', '')[:40],
                action.get('timeline', ''),
                action.get('expected_outcome', '')[:30],
                action.get('resources_needed', '')[:25]
            ])
        pdf.add_table(headers, rows, [55, 30, 55, 50])
    
    # 4-Week Plan
    pdf.add_page()
    pdf.chapter_title("4-Week Action Plan", "")
    
    weekly_plan = strategy.get('weekly_plan', [])
    for week in weekly_plan:
        week_num = week.get('week', 1)
        week_date = (today + timedelta(weeks=week_num - 1)).strftime('%b %d')
        
        pdf.section_title(f"Week {week_num} (Starting {week_date}): {week.get('focus_area', 'General')}")
        
        for task in week.get('tasks', []):
            pdf.checkbox_item(task)
        
        pdf.set_font('Helvetica', 'I', 9)
        pdf.set_text_color(34, 139, 34)  # Green
        pdf.ln(2)
        pdf.cell(0, 6, f"Success Metric: {week.get('success_metrics', 'Not specified')}", ln=True)
        pdf.set_text_color(0, 0, 0)
        pdf.ln(5)
    
    # Risks & Mitigations
    pdf.add_page()
    pdf.chapter_title("Risks & Mitigations", "")
    
    risks = strategy.get('risks_and_mitigations', [])
    if risks:
        headers = ['Risk', 'Likelihood', 'Impact', 'Mitigation']
        rows = []
        for risk in risks:
            rows.append([
                risk.get('risk', '')[:35],
                risk.get('likelihood', ''),
                risk.get('impact', ''),
                risk.get('mitigation', '')[:40]
            ])
        pdf.add_table(headers, rows, [50, 25, 25, 90])
    
    # Success Metrics
    pdf.chapter_title("Success Metrics", "")
    
    metrics = strategy.get('success_metrics', {})
    
    pdf.section_title("Short-term (1-4 weeks)")
    for metric in metrics.get('short_term', []):
        pdf.bullet_point(metric)
    
    pdf.ln(3)
    pdf.section_title("Long-term (1-3 months)")
    for metric in metrics.get('long_term', []):
        pdf.bullet_point(metric)
    
    # ROI
    pdf.ln(5)
    pdf.chapter_title("Estimated ROI", "")
    pdf.body_text(strategy.get('estimated_roi', 'ROI estimation not available.'))
    
    # Assumptions
    pdf.chapter_title("Key Assumptions", "")
    for assumption in strategy.get('assumptions', []):
        pdf.bullet_point(assumption)
    
    # Footer note
    pdf.ln(10)
    pdf.set_font('Helvetica', 'I', 9)
    pdf.set_text_color(128, 128, 128)
    pdf.multi_cell(0, 5, 
        f"This strategy was generated by MSME Copilot AI on {today.strftime('%B %d, %Y')} "
        "based on your sales data and autonomous market research. "
        "All recommendations are backed by verified sources."
    )
    
    # Return PDF as bytes
    return bytes(pdf.output())
